/*
 * Tracker API V1
 * Move your app forward with the gpi API
 *
 */


package com.swift.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Generated by SWIFT Standards 2017-03-22 00:13:52
 */
@ApiModel(description = "Generated by SWIFT Standards 2017-03-22 00:13:52")
public class CamtA0100102 {
  @SerializedName("update_payment_status_request")
  private UpdatePaymentStatusRequest updatePaymentStatusRequest = null;

  public CamtA0100102 updatePaymentStatusRequest(UpdatePaymentStatusRequest updatePaymentStatusRequest) {
    this.updatePaymentStatusRequest = updatePaymentStatusRequest;
    return this;
  }

   /**
   * Get updatePaymentStatusRequest
   * @return updatePaymentStatusRequest
  **/
  @ApiModelProperty(value = "")
  public UpdatePaymentStatusRequest getUpdatePaymentStatusRequest() {
    return updatePaymentStatusRequest;
  }

  public void setUpdatePaymentStatusRequest(UpdatePaymentStatusRequest updatePaymentStatusRequest) {
    this.updatePaymentStatusRequest = updatePaymentStatusRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CamtA0100102 camtA0100102 = (CamtA0100102) o;
    return Objects.equals(this.updatePaymentStatusRequest, camtA0100102.updatePaymentStatusRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(updatePaymentStatusRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CamtA0100102 {\n");
    
    sb.append("    updatePaymentStatusRequest: ").append(toIndentedString(updatePaymentStatusRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

