/*
 * Tracker API V1
 * Move your app forward with the gpi API
 *
 */


package com.swift.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Generated by SWIFT Standards 2017-06-29 13:18:18
 */
@ApiModel(description = "Generated by SWIFT Standards 2017-06-29 13:18:18")
public class CamtA0300102 {
  @SerializedName("get_payment_transactions_request")
  private GetPaymentTransactionsRequest getPaymentTransactionsRequest = null;

  public CamtA0300102 getPaymentTransactionsRequest(GetPaymentTransactionsRequest getPaymentTransactionsRequest) {
    this.getPaymentTransactionsRequest = getPaymentTransactionsRequest;
    return this;
  }

   /**
   * Get getPaymentTransactionsRequest
   * @return getPaymentTransactionsRequest
  **/
  @ApiModelProperty(value = "")
  public GetPaymentTransactionsRequest getGetPaymentTransactionsRequest() {
    return getPaymentTransactionsRequest;
  }

  public void setGetPaymentTransactionsRequest(GetPaymentTransactionsRequest getPaymentTransactionsRequest) {
    this.getPaymentTransactionsRequest = getPaymentTransactionsRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CamtA0300102 camtA0300102 = (CamtA0300102) o;
    return Objects.equals(this.getPaymentTransactionsRequest, camtA0300102.getPaymentTransactionsRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(getPaymentTransactionsRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CamtA0300102 {\n");
    
    sb.append("    getPaymentTransactionsRequest: ").append(toIndentedString(getPaymentTransactionsRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

