/*
 * Tracker API V1
 * Move your app forward with the gpi API
 *
 */

package com.swift.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Generated by SWIFT Standards 2017-03-22 00:13:52
 */
@ApiModel(description = "Generated by SWIFT Standards 2017-03-22 00:13:52")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-26T11:46:38.130-05:00")
public class CamtA0500202 {
  @SerializedName("get_invalid_events_response")
  private GetInvalidEventsResponse getInvalidEventsResponse = null;

  public CamtA0500202 getInvalidEventsResponse(GetInvalidEventsResponse getInvalidEventsResponse) {
    this.getInvalidEventsResponse = getInvalidEventsResponse;
    return this;
  }

   /**
   * Get getInvalidEventsResponse
   * @return getInvalidEventsResponse
  **/
  @ApiModelProperty(value = "")
  public GetInvalidEventsResponse getGetInvalidEventsResponse() {
    return getInvalidEventsResponse;
  }

  public void setGetInvalidEventsResponse(GetInvalidEventsResponse getInvalidEventsResponse) {
    this.getInvalidEventsResponse = getInvalidEventsResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CamtA0500202 camtA0500202 = (CamtA0500202) o;
    return Objects.equals(this.getInvalidEventsResponse, camtA0500202.getInvalidEventsResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(getInvalidEventsResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CamtA0500202 {\n");
    
    sb.append("    getInvalidEventsResponse: ").append(toIndentedString(getInvalidEventsResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

