/*
 * Tracker API V1
 * Move your app forward with the gpi API
 *
 */


package com.swift.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Generated by SWIFT Standards 2017-03-22 00:13:52
 */
@ApiModel(description = "Generated by SWIFT Standards 2017-03-22 00:13:52")
public class CamtA0200202 {
  @SerializedName("get_payment_transaction_details_response")
  private GetPaymentTransactionDetailsResponse getPaymentTransactionDetailsResponse = null;

  public CamtA0200202 getPaymentTransactionDetailsResponse(GetPaymentTransactionDetailsResponse getPaymentTransactionDetailsResponse) {
    this.getPaymentTransactionDetailsResponse = getPaymentTransactionDetailsResponse;
    return this;
  }

   /**
   * Get getPaymentTransactionDetailsResponse
   * @return getPaymentTransactionDetailsResponse
  **/
  @ApiModelProperty(value = "")
  public GetPaymentTransactionDetailsResponse getGetPaymentTransactionDetailsResponse() {
    return getPaymentTransactionDetailsResponse;
  }

  public void setGetPaymentTransactionDetailsResponse(GetPaymentTransactionDetailsResponse getPaymentTransactionDetailsResponse) {
    this.getPaymentTransactionDetailsResponse = getPaymentTransactionDetailsResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CamtA0200202 camtA0200202 = (CamtA0200202) o;
    return Objects.equals(this.getPaymentTransactionDetailsResponse, camtA0200202.getPaymentTransactionDetailsResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(getPaymentTransactionDetailsResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CamtA0200202 {\n");
    
    sb.append("    getPaymentTransactionDetailsResponse: ").append(toIndentedString(getPaymentTransactionDetailsResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

