/*
 * Tracker API V1
 * Move your app forward with the gpi API
 *
 * OpenAPI spec version: 1.2.37
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.swift.model.GetInvalidEventsRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Generated by SWIFT Standards 2017-03-22 00:13:52
 */
@ApiModel(description = "Generated by SWIFT Standards 2017-03-22 00:13:52")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-26T11:46:38.130-05:00")
public class CamtA0500102 {
  @SerializedName("get_invalid_events_request")
  private GetInvalidEventsRequest getInvalidEventsRequest = null;

  public CamtA0500102 getInvalidEventsRequest(GetInvalidEventsRequest getInvalidEventsRequest) {
    this.getInvalidEventsRequest = getInvalidEventsRequest;
    return this;
  }

   /**
   * Get getInvalidEventsRequest
   * @return getInvalidEventsRequest
  **/
  @ApiModelProperty(value = "")
  public GetInvalidEventsRequest getGetInvalidEventsRequest() {
    return getInvalidEventsRequest;
  }

  public void setGetInvalidEventsRequest(GetInvalidEventsRequest getInvalidEventsRequest) {
    this.getInvalidEventsRequest = getInvalidEventsRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CamtA0500102 camtA0500102 = (CamtA0500102) o;
    return Objects.equals(this.getInvalidEventsRequest, camtA0500102.getInvalidEventsRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(getInvalidEventsRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CamtA0500102 {\n");
    
    sb.append("    getInvalidEventsRequest: ").append(toIndentedString(getInvalidEventsRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

