/*
 * Tracker API V1
 * Move your app forward with the gpi API
 *
 */


package com.swift.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Generated by SWIFT Standards 2017-03-22 00:13:52
 */
@ApiModel(description = "Generated by SWIFT Standards 2017-03-22 00:13:52")
public class CamtA0200102 {
  @SerializedName("get_payment_transaction_details_request")
  private GetPaymentTransactionDetailsRequest getPaymentTransactionDetailsRequest = null;

  public CamtA0200102 getPaymentTransactionDetailsRequest(GetPaymentTransactionDetailsRequest getPaymentTransactionDetailsRequest) {
    this.getPaymentTransactionDetailsRequest = getPaymentTransactionDetailsRequest;
    return this;
  }

   /**
   * Get getPaymentTransactionDetailsRequest
   * @return getPaymentTransactionDetailsRequest
  **/
  @ApiModelProperty(value = "")
  public GetPaymentTransactionDetailsRequest getGetPaymentTransactionDetailsRequest() {
    return getPaymentTransactionDetailsRequest;
  }

  public void setGetPaymentTransactionDetailsRequest(GetPaymentTransactionDetailsRequest getPaymentTransactionDetailsRequest) {
    this.getPaymentTransactionDetailsRequest = getPaymentTransactionDetailsRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CamtA0200102 camtA0200102 = (CamtA0200102) o;
    return Objects.equals(this.getPaymentTransactionDetailsRequest, camtA0200102.getPaymentTransactionDetailsRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(getPaymentTransactionDetailsRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CamtA0200102 {\n");
    
    sb.append("    getPaymentTransactionDetailsRequest: ").append(toIndentedString(getPaymentTransactionDetailsRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

