/*
 * Tracker API V1
 * Move your app forward with the gpi API
 *
 * OpenAPI spec version: 1.2.37
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.swift.model.GetChangedPaymentTransactionsRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Generated by SWIFT Standards 2017-06-29 13:18:18
 */
@ApiModel(description = "Generated by SWIFT Standards 2017-06-29 13:18:18")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-26T11:46:38.130-05:00")
public class CamtA0400102 {
  @SerializedName("get_changed_payment_transactions_request")
  private GetChangedPaymentTransactionsRequest getChangedPaymentTransactionsRequest = null;

  public CamtA0400102 getChangedPaymentTransactionsRequest(GetChangedPaymentTransactionsRequest getChangedPaymentTransactionsRequest) {
    this.getChangedPaymentTransactionsRequest = getChangedPaymentTransactionsRequest;
    return this;
  }

   /**
   * Get getChangedPaymentTransactionsRequest
   * @return getChangedPaymentTransactionsRequest
  **/
  @ApiModelProperty(value = "")
  public GetChangedPaymentTransactionsRequest getGetChangedPaymentTransactionsRequest() {
    return getChangedPaymentTransactionsRequest;
  }

  public void setGetChangedPaymentTransactionsRequest(GetChangedPaymentTransactionsRequest getChangedPaymentTransactionsRequest) {
    this.getChangedPaymentTransactionsRequest = getChangedPaymentTransactionsRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CamtA0400102 camtA0400102 = (CamtA0400102) o;
    return Objects.equals(this.getChangedPaymentTransactionsRequest, camtA0400102.getChangedPaymentTransactionsRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(getChangedPaymentTransactionsRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CamtA0400102 {\n");
    
    sb.append("    getChangedPaymentTransactionsRequest: ").append(toIndentedString(getChangedPaymentTransactionsRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

