/*
 * Tracker API V1
 * Move your app forward with the gpi API
 *
 * OpenAPI spec version: 1.2.37
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.swift.model.PaymentEvent3;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * This API is a payment events response to a query to get invalid events for payment transactions within a given time frame. An event is either a payment or a status confirmation.[CR][LF]The API is typically used for support or audit purposes, where all invalid messages sent or received are retrievable by one API call.[CR][LF]
 */
@ApiModel(description = "This API is a payment events response to a query to get invalid events for payment transactions within a given time frame. An event is either a payment or a status confirmation.[CR][LF]The API is typically used for support or audit purposes, where all invalid messages sent or received are retrievable by one API call.[CR][LF]")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-26T11:46:38.130-05:00")
public class GetInvalidEventsResponse {
  @SerializedName("event")
  private List<PaymentEvent3> event = new ArrayList<PaymentEvent3>();

  public GetInvalidEventsResponse event(List<PaymentEvent3> event) {
    this.event = event;
    return this;
  }

  public GetInvalidEventsResponse addEventItem(PaymentEvent3 eventItem) {
    this.event.add(eventItem);
    return this;
  }

   /**
   * Each instance contains one payment event that matches the search criteria.
   * @return event
  **/
  @ApiModelProperty(required = true, value = "Each instance contains one payment event that matches the search criteria.")
  public List<PaymentEvent3> getEvent() {
    return event;
  }

  public void setEvent(List<PaymentEvent3> event) {
    this.event = event;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetInvalidEventsResponse getInvalidEventsResponse = (GetInvalidEventsResponse) o;
    return Objects.equals(this.event, getInvalidEventsResponse.event);
  }

  @Override
  public int hashCode() {
    return Objects.hash(event);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetInvalidEventsResponse {\n");
    
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

